name: Chrome
on: push

jobs:
  chrome:
    runs-on: actuated
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - run: |
        sudo apt update -qqy && apt-get install -qqy --no-install-recommends libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: ./example.js
